# Redirect all routes to index.html for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sgfs/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
