[package]
name = "calm-go-patterns-common"
version = "0.1.0"
edition = "2024"

[dependencies]
bit-vec = "0.6"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

[dev-dependencies]
proptest = "1.4.0"
