[package]
name = "calm-go-patterns-pack-games"
version = "0.1.0"
edition = "2024"

[dependencies]
calm-go-patterns-common = { version = "0.1.0", path = "../common" }
jwalk = "0.8.1"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
sgf-parse = "4.2.3"
