[package]
name = "calm-go-patterns-pack-games"
version = "0.1.0"
edition = "2024"

[dependencies]
calm-go-patterns-common = { path = "../common" }
jwalk = "0.8.1"
rayon = "1.10.0"
sgf-parse = "4.2.3"
