name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy,rustfmt"

      - name: Unpack player_names.json
        run: cd rust/pack-games/python-player-name-aliases/ && gunzip player_names.json.gz

      - name: Run clippy
        run: |
          touch rust/wasm-search/src/games.pack
          cargo clippy --version
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build wasm
        run: yarn wasm

      - name: Install dependencies
        run: cd frontend && yarn install --frozen-lockfile

      - name: Type check
        run: cd frontend && yarn tsc --noEmit

      - name: Lint
        run: cd frontend && yarn lint --max-warnings 0

      - name: Check formatting
        run: yarn fmt:check
